### ISSUE TITLE
Page 2: Description of critical systems looses reader

### ISSUE THREAD

**Issue by pht-uol** [NFDI4Energy/EFZN_rdm#45] opened 2023-07-27 12:46 UTC
In the second paragraph, some kind of critical systems fail due to "overload of critical systems". However, the text does not lead the reader and she remains unknown of what kind of systems she should have in mind. This costs important attention so early in the course.

**Comment by JuliaHeiken** [comment] 2023-07-28 08:36
The issue is also addressed in https://github.com/NFDI4Energy/EFZN_rdm/issues/11.

**Closed** 2023-09-08 08:39 UTC
Labels: critical issue
